CREATE TABLE Book
(
    id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ISBN        varchar(17) UNIQUE NOT NULL,
    name        varchar(50)        NOT NULL,
    genre       varchar(50)        NOT NULL,
    description varchar(200)       NOT NULL,
    author      varchar(50)        NOT NULL,
    deleted     bool               NOT NULL
);

CREATE TABLE book_info
(
    book_id           int PRIMARY KEY,
    status            bool,
    received_at       timestamp,
    time_to_give_back timestamp,
    deleted           bool
);
CREATE TABLE Person
(
    id       int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(250) NOT NULL,
    password varchar(250) NOT NULL
);